version: 0.2

phases:
  install:
    commands:
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
      - export NVM_DIR="$HOME/.nvm" 
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm 
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion 
      - nvm install 8.15.0
      - apt-get install -y npm
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - node server/index.js